version: "3.3"
services:
  # Rasa Server
  rasa:
    image: rasa/rasa:1.7.0-full
    ports:
      - 5005:5005
    network_mode: host
    volumes:
      - ./bot:/app
    command:
      - run
      - --enable-api
      - --endpoint
      - endpoints.yml
      - --model
      - models/
      - --debug
  # Rasa Action Server
  action_server:
    image: rasa/rasa-sdk:1.7.0
    ports:
      - 5055:5055
    volumes:
      - ./bot/actions:/app/actions/actions
  # MongoDB
  mongo:
    image: mongo
    volumes:
      - $HOME/chatbot_workshop/fruit_bot_stack/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rasa
      MONGO_INITDB_ROOT_PASSWORD: rasa_password
  # Mongo GUI
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rasa
      ME_CONFIG_MONGODB_ADMINPASSWORD: rasa_password
      ME_CONFIG_MONGODB_SERVER: mongo
  # Redis Lock Store
  redis:
    restart: always
    image: bitnami/redis:5.0.7
    ports:
      - "6379:6379"
    volumes:
      - $HOME/chatbot_workshop/fruit_bot_stack/redis.conf:/opt/bitnami/redis/etc/redis.conf
    environment:
      REDIS_PASSWORD: rasa_password
  # Rabbit Pika Event Broker
  rabbit:
    restart: always
    image: "bitnami/rabbitmq:3.7.17"
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_USERNAME: rasa
      RABBITMQ_PASSWORD: rasa_password
      RABBITMQ_DISK_FREE_LIMIT: "{mem_relative, 0.1}"
    ports:
      - "5672:5672"
  # Nginx Reverse Proxy
  nginx:
    restart: always
    hostname: reverse
    image: nginx
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - $HOME/chatbot_workshop/fruit_bot_stack/nginx/conf/conf.d:/etc/nginx/conf.d
      - $HOME/chatbot_workshop/fruit_bot_stack/nginx/conf/partials:/etc/nginx/partials
      - $HOME/chatbot_workshop/fruit_bot_stack/nginx/certbot/conf:/etc/letsencrypt
      - $HOME/chatbot_workshop/fruit_bot_stack/nginx/certbot/www:/var/www/certbot
      - $HOME/chatbot_workshop/fruit_bot_stack/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  # Letsencrypt renewal bot - https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - $HOME/chatbot_workshop/fruit_bot_stack/nginx/certbot/conf:/etc/letsencrypt
      - $HOME/chatbot_workshop/fruit_bot_stack/nginx/certbot/www:/var/www/certbot
